apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  annotations:
    argocd-image-updater.argoproj.io/image-list: "api-image=891376983113.dkr.ecr.us-east-1.amazonaws.com/demoapp"
    argocd-image-updater.argoproj.io/api-image.update-strategy: latest
    argocd-image-updater.argoproj.io/api-image.kustomize.image-name: "application-image"
    argocd-image-updater.argoproj.io/api-image.force-update: "true"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    targetRevision: main
    repoURL: git@github.com:neeltom92/demoapp-manifests.git 
    path: manifests/prod
